root = "."
testdata_dir = "testdata"
tmp_dir = "./tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules","ui"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = false
  proxy_port = 8090
  app_port = 8080

[screen]
  clear_on_rebuild = false
  keep_scroll = true

# Watch directories
[[build.watch_dirs]]
  dir = "."
  
[[build.watch_dirs]]
  dir = "../../core"
  
[[build.watch_dirs]]
  dir = "./handlers"
  
[[build.watch_dirs]]
  dir = "./integrations"
  
[[build.watch_dirs]]
  dir = "./lib"
  
[[build.watch_dirs]]
  dir = "./plugins"

[[build.watch_dirs]]
  dir = "../../ui"